
package visao;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categoria;


public class FrmGerenciarCategoria extends javax.swing.JFrame {

   private Categoria objetocategoria;
    public FrmGerenciarCategoria() {
        initComponents();
        this.objetocategoria = new Categoria(); // carrega objetoaluno de aluno
        this.carregaTabela();
    }
     public void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.JTCategoria.getModel();
        modelo.setNumRows(0); //Posiciona na primeira linha da tabela
//Carrega a lista de objetos aluno
        ArrayList<Categoria> minhaLista = objetocategoria.getMinhaLista();
        for (Categoria c : minhaLista) {
            modelo.addRow(new Object[]{
                c.getIdCategoria(),
                c.getNome(),
                c.getTamanho(),
                c.getEmbalagem()
                
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLNomeUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTCategoria = new javax.swing.JTable();
        JLNomeUser1 = new javax.swing.JLabel();
        JLNomeUser2 = new javax.swing.JLabel();
        JTFNome = new javax.swing.JTextField();
        JTFEmbalagem = new javax.swing.JTextField();
        JBAlterar = new javax.swing.JButton();
        JBCancelar = new javax.swing.JButton();
        JBApagar = new javax.swing.JButton();
        JLNomeUser3 = new javax.swing.JLabel();
        JTFTamanho = new javax.swing.JTextField();

        JLNomeUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLNomeUser.setText("Nome:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JTCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "EMBALAGEM", "TAMANHO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTCategoria.setToolTipText("");
        JTCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTCategoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTCategoria);

        JLNomeUser1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLNomeUser1.setText("Tamanho:");

        JLNomeUser2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLNomeUser2.setText("Embalagem:");

        JTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFNomeActionPerformed(evt);
            }
        });

        JTFEmbalagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFEmbalagemActionPerformed(evt);
            }
        });

        JBAlterar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBAlterar.setText("Alterar");
        JBAlterar.setPreferredSize(new java.awt.Dimension(92, 32));
        JBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAlterarActionPerformed(evt);
            }
        });

        JBCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBCancelar.setText("Cancelar");
        JBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBCancelarActionPerformed(evt);
            }
        });

        JBApagar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        JBApagar.setText("Apagar");
        JBApagar.setPreferredSize(new java.awt.Dimension(92, 32));
        JBApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBApagarActionPerformed(evt);
            }
        });

        JLNomeUser3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLNomeUser3.setText("Nome:");

        JTFTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JLNomeUser1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                        .addComponent(JLNomeUser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLNomeUser3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                    .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTFTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(JBAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBApagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBCancelar, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLNomeUser3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(JLNomeUser1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTFTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JLNomeUser2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(JBCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JTFEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(JBAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(JBApagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)))
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFNomeActionPerformed

    private void JTFEmbalagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFEmbalagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFEmbalagemActionPerformed

    private void JBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_JBCancelarActionPerformed

    private void JTFTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFTamanhoActionPerformed

    private void JBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAlterarActionPerformed
        try {
            // recebendo e validando dados da interface gr�fica.
           int idCategoria = 0;
        String nome = "";
        String embalagem = "";
        String tamanho = "";
        

        if (this.JTFNome.getText().length() < 2) {
            throw new Mensagem("Nome deve conter ao menos 2 caracteres.");
        } else {
            nome = this.JTFNome.getText();
        }

        if (this.JTFEmbalagem.getText().length() <= 0) {
            throw new Mensagem("Embalagem deve ter ao menos 2 caracteres");
        } else {
            embalagem = this.JTFEmbalagem.getText();
        }

        if (this.JTFTamanho.getText().length() < 2) {
            throw new Mensagem("Tamanho deve conter ao menos 2 caracteres.");
        } else {
            tamanho = this.JTFTamanho.getText();
        }

        if (this.JTCategoria.getSelectedRow() == -1) {
            throw new Mensagem("Primeiro Selecione uma Categoria para Alterar");
        } else {
            idCategoria = Integer.parseInt(this.JTCategoria.getValueAt(this.JTCategoria.getSelectedRow(), 0).toString());
        }

        // envia os dados para a categoria processar
        if (this.objetocategoria.updatecategoria(idCategoria, nome, embalagem, tamanho)) {
            // limpa os campos
            this.JTFNome.setText("");
            this.JTFEmbalagem.setText("");
            this.JTFTamanho.setText(""); 
            JOptionPane.showMessageDialog(null, "Categoria Alterada com Sucesso!");

        }
        // Exibe no console a categoria cadastrada
        System.out.println(this.objetocategoria.getMinhaLista().toString());
    }
        
        catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número válido.");
    }
    catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
    }
    

        finally {
            // atualiza a tabela.
            carregaTabela();
    }
    }//GEN-LAST:event_JBAlterarActionPerformed

    private void JBApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBApagarActionPerformed
         try {
            // validando dados da interface gráfica.
            int idCategoria = 0;
            if (this.JTCategoria.getSelectedRow() == -1) {
                throw new Mensagem("Primeiro Selecione uma Categoria para APAGAR");
            } else {
                idCategoria = Integer.parseInt(this.JTCategoria.getValueAt(this.JTCategoria.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro botão | 1 -> segundo botão | 2 -> terceiro botão
            int respostaUsuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja apagar esta Categoria ?");

            if (respostaUsuario == 0) {// clicou em SIM
                // envia os dados para a categoria processar
                if (this.objetocategoria.deleteCategoria(idCategoria)) {
                    // limpa os campos
                    this.JTFNome.setText("");
                    this.JTFEmbalagem.setText("");
                    this.JTFTamanho.setText("");
                    
                    JOptionPane.showMessageDialog(rootPane, "Categoria Apagada com Sucesso!");
                }
            }
            // atualiza a tabela.
            System.out.println(this.objetocategoria.getMinhaLista().toString());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_JBApagarActionPerformed

    private void JTCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTCategoriaMouseClicked
         if (this.JTCategoria.getSelectedRow() != -1) {
            String nome = this.JTCategoria.getValueAt(this.JTCategoria.getSelectedRow(), 1).toString();
            String embalagem = this.JTCategoria.getValueAt(this.JTCategoria.getSelectedRow(), 2).toString();
            String tamanho = this.JTCategoria.getValueAt(this.JTCategoria.getSelectedRow(), 3).toString();

            this.JTFNome.setText(nome);
            this.JTFEmbalagem.setText(embalagem);
            this.JTFTamanho.setText(tamanho);
        }
    }//GEN-LAST:event_JTCategoriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGerenciarCategoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAlterar;
    private javax.swing.JButton JBApagar;
    private javax.swing.JButton JBCancelar;
    private javax.swing.JLabel JLNomeUser;
    private javax.swing.JLabel JLNomeUser1;
    private javax.swing.JLabel JLNomeUser2;
    private javax.swing.JLabel JLNomeUser3;
    private javax.swing.JTable JTCategoria;
    private javax.swing.JTextField JTFEmbalagem;
    private javax.swing.JTextField JTFNome;
    private javax.swing.JTextField JTFTamanho;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
